{% set name = "pypolymlp" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pypolymlp-{{ version }}.tar.gz
  sha256: bf50de8168b1bb687f9c3edcb47ffdf46a7f458a980eefd1c7f0fb6a0763b51f

build:
  skip: true  # [py<39 or win]
  entry_points:
    - pypolymlp=pypolymlp.api.run_polymlp:run
    - pypolymlp-calc=pypolymlp.api.run_polymlp_calc:run
    - pypolymlp-utils=pypolymlp.api.run_polymlp_utils:run
    - pypolymlp-structure=pypolymlp.api.run_polymlp_str:run
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cmake
    - make
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - python
    - setuptools >=61.0
    - scikit-build
    - wheel
    - cmake
    - pybind11
    - pybind11-global
    - eigen
    - pip
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  run:
    - python
    - pybind11
    - pybind11-global
    - eigen
    - scipy
    - pyyaml
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pypolymlp
  commands:
    - pip check
    - pypolymlp --help
    - pypolymlp-calc --help
    - pypolymlp-utils --help
    - pypolymlp-structure --help
  requires:
    - pip

about:
  home: https://github.com/sekocha/pypolymlp
  summary: Generator of polynomial machine learning potentials.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sekocha
