#!/usr/bin/env python
import numpy as np
import itertools

def refine_positions(positions, tol=1e-13):
    positions -= np.floor(positions)
    positions[np.where(positions > 1-tol)] -= 1.0
    return positions

def make_supercell(unitcell, size):

    mat = np.diag(size)
    n_expand = np.prod(size)

    supercell = dict()
    supercell['axis'] = np.dot(unitcell['axis'], mat)

    translations = list(itertools.product(range(size[0]), 
                                          range(size[1]), 
                                          range(size[2])))
    positions_new = []
    for pos in unitcell['positions'].T:
        for trans in translations:
            pos_new = (pos + np.array(trans)) / np.array(size)
            positions_new.append(pos_new)
    supercell['positions'] = np.array(positions_new).T

    supercell['n_atoms'] =  np.array(unitcell['n_atoms']) * n_expand
    if unitcell['types'] is not None:
        supercell['types'] = [n for n in unitcell['types'] 
                                for i in range(n_expand)]
    if unitcell['elements'] is not None:
        supercell['elements'] = [n for n in unitcell['elements']
                                   for i in range(n_expand)]
    if unitcell['volume'] is not None:
        supercell['volume'] = unitcell['volume'] * n_expand

    return supercell

def print_poscar_tofile(st, filename='poscar_pypolymlp', 
                        header=None,
                        print_zero_atom=True):

    f = open(filename, 'w')

    if header is None and st['comment'] is None:
        print('Generated by pypolymlp', file=f)
    elif header is None:
        print(st['comment'], file=f)
    else:
        print(header, file=f)

    print('1.0', file=f)
    for n in st['axis'].T:
        print("  ", "{0:15.15f}".format(n[0]),
                    "{0:15.15f}".format(n[1]), 
                    "{0:15.15f}".format(n[2]), file=f)

    index=0
    print(' ', end='', file=f)
    for n in st['n_atoms']:
        if n > 0:
            print(st['elements'][index], " ", end='', file=f)
            index += n
        elif print_zero_atom:
            print("NoEle  ", end='', file=f)
    print('', file=f)

    print(' ', end='', file=f)
    for n in st['n_atoms']:
        if n > 0:
            print(n, ' ', end='', file=f)
        elif print_zero_atom:
            print(n, ' ', end='', file=f)
    print('', file=f)

    print('Direct', file=f)
    for n in refine_positions(st['positions']).T:
        print("  ", "{0:15.15f}".format(float(n[0])), 
                    "{0:15.15f}".format(float(n[1])), 
                    "{0:15.15f}".format(float(n[2])), file=f)
    f.close()

