name: publish PyPI and TestPyPI

on:
  push:
    branches:
    - master
    - rc

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Make sdist
      run: |
        git tag v`grep "__version__ = version" _version.py | awk '{print $5}'`
        pip install build
        python -m build --sdist
    - name: Publish package to TestPyPI
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/rc')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
